theme: jekyll-theme-minimal
title: Pilvipalvelut web-kehityksessä
description: Tänne ilmestyy viikkotehtävien lisäksi kurssin harjoitustyö!

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

matomo:
  enabled: true
  url: 'https://pilvipalvelut-matomo.rahtiapp.fi/'
  siteId: 13
